# -*- coding: utf-8 -*-
"""python_streamlit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j8fvasSsbmjHDVjWTIuv_c8111dgyvhp
"""

import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
data = pd.DataFrame({
    'employee_id': range(1, 101),
    'experience_years': np.random.randint(1, 15, 100),
    'salary': np.random.randint(30000, 120000, 100),
    'department': np.random.choice(['HR', 'IT', 'Sales', 'Marketing'], 100)
})

data

st.set_page_config(page_title='Employee Dashboard', layout='wide')

st.title('Employee Analytics Dashboard')

col1, col2, col3 = st.columns(3)

col1.metric('Total Employees',len(data))
col2.metric('Average Employee (Years)',round(data['experience_years'].mean(),1))
col3.metric('Average Salary',round(data['salary'].mean(),0))


st.subheader('Salary vs Experience by Department')
figure_1 = px.scatter(data, x='experience_years', y='salary', color='department', title='Salary vs Experience', labels={'experience_years': 'Experience (Years)', 'salary': 'Salary'}
           , hover_data=['employee_id'])

st.plotly_chart(figure_1, use_container_width=True)


st.subheader('Department Distribution')

figure_2 = px.histogram(
    data, x='department', title='Department Distribution', labels={'department': 'Department'},
    color = 'department')
st.plotly_chart(figure_2, use_container_width=True)

st.subheader('Employee Data')
st.dataframe(data)

